var name = "shashank";
var school = "cbse";
var grade = "10th class";
var section = "B";
var roolno = 38;
var marks1 = 99;
var marks2 = 98;
var marks3 = 89;
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(roolno);
console.log(marks1);
console.log(marks2);
console.log(marks3);